service: tasks-ui

frameworkVersion: '4'
useDotenv: true


provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'development'}



custom:
  stage: ${opt:stage, self:provider.stage}
  bucketName: ${self:custom.stage}-${aws:accountId}-tasks-api


resources:
  Resources:
    TasksAPIBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
  Outputs:
    TasksAPIBucketName:
      Value: !Ref TasksAPIBucket
      Export:
        Name: s3-${self:custom.bucketName}-name
    TasksAPIBucketArn:
      Value: !GetAtt TasksAPIBucket.Arn
      Export:
        Name: s3-${self:custom.bucketName}-arn